# Generated by Django 4.0.1 on 2022-01-13 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='envelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('transaction_type', models.CharField(max_length=9)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('debit_or_credit', models.CharField(max_length=6)),
                ('purchase_method', models.CharField(max_length=15)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.envelope')),
            ],
        ),
    ]
